(test_map.cpp, 263): loadFactorMin > hashLoadFactor: File exists
(test_map.cpp, 263): loadFactorMin > hashLoadFactor: File exists
(test_map.cpp, 263): loadFactorMin > hashLoadFactor: File exists
(test_map.cpp, 263): loadFactorMin > hashLoadFactor: File exists
Traceback (most recent call last):
  File "bench.py", line 72, in <module>
    output = subprocess.check_output(['./' + program, testEntries, testChunks, testSpeed])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./gpu_hashtable', '1000000', '1', '10']' returned non-zero exit status 17.
Traceback (most recent call last):
  File "bench.py", line 72, in <module>
    output = subprocess.check_output(['./' + program, testEntries, testChunks, testSpeed])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./gpu_hashtable', '1000000', '2', '20']' returned non-zero exit status 17.
Traceback (most recent call last):
  File "bench.py", line 72, in <module>
    output = subprocess.check_output(['./' + program, testEntries, testChunks, testSpeed])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./gpu_hashtable', '10000000', '4', '50']' returned non-zero exit status 17.
Traceback (most recent call last):
  File "bench.py", line 72, in <module>
    output = subprocess.check_output(['./' + program, testEntries, testChunks, testSpeed])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./gpu_hashtable', '40000000', '2', '50']' returned non-zero exit status 17.
